### ISSUE TITLE
Error in test script

### ISSUE THREAD

**Issue by huggre** [GrandMoff100/HomeAssistantAPI#1]
Hi, get this error when trying your example code, any idea?
Do you have any additional documentation for this library?

```
C:\PythonApps\home_ass>python wrapper_test.py
Traceback (most recent call last):
  File "C:\PythonApps\home_ass\wrapper_test.py", line 11, in <module>
    client = Client(url, token)
  File "C:\Users\Hugo\AppData\Local\Programs\Python\Python39\lib\site-packages\homeassistant_api\rawclient.py", line 58, in __init__
    self.check_api_config()
  File "C:\Users\Hugo\AppData\Local\Programs\Python\Python39\lib\site-packages\homeassistant_api\rawclient.py", line 80, in check_api_config
    valid = {'valid': True, 'invalid': False}.get(res['result'], None)
TypeError: string indices must be integers
```

**Comment by GrandMoff100** [comment]
I apologize. I am just getting around to this. Hmm, that is peculiar. Could you verify that you set the environmental variables correctly?

I agree there I do need to add more documentation. I didn't realize other people used this but me. Haha. But I'm happy to help.

I also assume that you correctly configured your Homeassistant to run its API server, correct?
[Homeassistant API server docs](https://developers.home-assistant.io/docs/api/rest/)
[API Plugin docs](https://www.home-assistant.io/integrations/api)

**Comment by GrandMoff100** [comment]
Closing this issues because extensive documentation is being released soon and big changes have happened in the repository and we feel that this issue is somewhat resolved or is about be at least

**Comment by GrandMoff100** [comment]
## [MegaLinter](https://megalinter.github.io) status: ✅ [**SUCCESS**](https://github.com/GrandMoff100/HomeAssistantAPI/actions/runs/1914073785)

|  Descriptor  |                                                Linter                                                |Files|Fixed|Errors|Elapsed time|
|--------------|------------------------------------------------------------------------------------------------------|-----|----:|------|------------|
|✅ ACTION     |[actionlint](https://megalinter.github.io/descriptors/action_actionlint)                              |    4|     |     0|0.05s       |
|✅ CREDENTIALS|[secretlint](https://megalinter.github.io/descriptors/credentials_secretlint)                         |yes  |     |no    |0.86s       |
|✅ GIT        |[git_diff](https://megalinter.github.io/descriptors/git_git_diff)                                     |yes  |     |no    |0.01s       |
|✅ JSON       |[eslint-plugin-jsonc](https://megalinter.github.io/descriptors/json_eslint_plugin_jsonc)              |2    |    0|     0|1.02s       |
|✅ JSON       |[jsonlint](https://megalinter.github.io/descriptors/json_jsonlint)                                    |2    |     |     0|0.58s       |
|✅ JSON       |[prettier](https://megalinter.github.io/descriptors/json_prettier)                                    |2    |    0|     0|1.07s       |
|✅ JSON       |[v8r](https://megalinter.github.io/descriptors/json_v8r)                                              |2    |     |     0|2.09s       |
|✅ MARKDOWN   |[markdownlint](https://megalinter.github.io/descriptors/markdown_markdownlint)                        |6    |    0|     0|0.41s       |
|✅ MARKDOWN   |[markdown-link-check](https://megalinter.github.io/descriptors/markdown_markdown_link_check)          |6    |     |     0|1.95s       |
|✅ MARKDOWN   |[markdown-table-formatter](https://megalinter.github.io/descriptors/markdown_markdown_table_formatter)|6    |    0|     0|0.3s        |
|✅ SPELL      |[misspell](https://megalinter.github.io/descriptors/spell_misspell)                                   |26   |    0|     0|0.07s       |
|✅ YAML       |[prettier](https://megalinter.github.io/descriptors/yaml_prettier)                                    |7    |    0|     0|1.29s       |
|✅ YAML       |[v8r](https://megalinter.github.io/descriptors/yaml_v8r)                                              |7    |     |     0|6.4s        |
|✅ YAML       |[yamllint](https://megalinter.github.io/descriptors/yaml_yamllint)                                    |7    |     |     0|0.18s       |


See errors details in [**artifact MegaLinter reports** on CI Job page](https://github.com/GrandMoff100/HomeAssistantAPI/actions/runs/1914073785)
