### ISSUE TITLE
[Library Bug] Not all service fields have descriptions

### ISSUE THREAD

**Issue by Azimath** [GrandMoff100/HomeAssistantAPI#120]
**Describe the bug**
The library assumes that all service fields have a description, and pyDantic will throw an exception if you get one that doesn't. Home assistant returns null for these descriptions, and python parses this as None.
I use some ESPHome devices, which create services with undescribed fields and there isn't a way to set one. Changing ServiceField description to Optional[str] instead of str works for me but I'm not sure if that would have further ramifications. This happens while fetching an unrelated service domain, as all domains are fetched and parsed including the custom ones.

**To Reproduce**
1. Have a device that advertises a service with fields that have no description (e.g. an esphome device that advertises a service).
2. Connect to the HA API.
3. Get any service domain.

**Expected behavior**
I expect that the API wouldn't raise an exception and would at least work for unrelated domains.

**Desktop (please complete the following information):**
- OS: Windows 10
- OS Version: 10.0.19044
- HomeAssistantAPI Version: 4.0.0.post1

**Comment by GrandMoff100** [comment]
Oh cool. I didn't realize that services were able to not have a description. Yeah, no there shouldn't be any ramifications implementing the solution you described. I would welcome a PR with it if you want to, otherwise it might take a little bit longer for me to sit down and fix it.

**Comment by Azimath** [comment]
#121 fixes this
