### ISSUE TITLE
[Library Bug] ensure this value has at most 26 characters (type=value_error.any_str.max_length; limit_value=26)

### ISSUE THREAD

**Issue by ndbroadbent** [GrandMoff100/HomeAssistantAPI#128]
**Describe the bug**

The library is crashing for me with a length validation. Could this be increased to a larger limit?

https://github.com/GrandMoff100/HomeAssistantAPI/blob/b949d3fc2d5cb96efe22b2ed0da6c7a87c159c16/homeassistant_api/models/states.py#L13

I forked the repo and increased the limit to 128, and this fixed the crash for me.

**Comment by GrandMoff100** [comment]
For sure. That number was arbitrary when I initially developed it and never encountered a case that required it to be increased. But now I see that there is. Feel free to open a PR with your repos increased limit!

**Comment by ndbroadbent** [comment]
@GrandMoff100 Thanks! I can see that you already opened a PR here: https://github.com/GrandMoff100/HomeAssistantAPI/pull/129
LGTM!
