### ISSUE TITLE
polling state stuck in a loop

### ISSUE THREAD

**Issue by N4S4** [GrandMoff100/HomeAssistantAPI#147]
Hi tnx for the repo!

dunno where to categorize this and I don't if i am the only one to have this issue,

I am following the example from documentation:

```
from datetime import datetime
from homeassistant_api import Client

 # You can also initialize Client before you use it.

 client = Client("https://foobarhomeassistant.duckdns.org:8123/api", "mylongtokenpasswordthingyfoobar")

 # In order to activate the requests session you to use the Client context manager like so.
 # Using it as a context manager will automatically close the session when you're done with it.
 # But also will *ping* your Home Assistant instance to make sure it's running.
 with client:
     while True:
         sun = client.get_entity(entity_id="sun.sun")
         state = sun.get_state()  # Because requests are cached we reduce bandwidth usage :D
         # Cache expires every 30 seconds by default.
         if state.state == "below_horizon":
             difference = datetime.now() - state.last_updated
             print("Sun set", difference.seconds, "seconds ago.")
             break
```

It remains stuck in the loop, if i add some prints i see the actual state never changes even waiting more than 30 seconds.
Am I missing something?

**Comment by GrandMoff100** [comment]
Will you format your code example for readability, please?

**Comment by GrandMoff100** [comment]
Thank you. Just curious, what's your source for the 30 second default cache?

**Comment by N4S4** [comment]
I just used the example from docs, when I run it, if the state changes from 'above-horizont" to "below_horizont" the loop does not stop and it runs for ever

**Comment by GrandMoff100** [comment]
Interesting. I will try to reproduce this later today.

**Comment by N4S4** [comment]
How can I change the cache refresh time?

[EDIT] 
ok i see from documentation should be `cache_session` param, is it in seconds? 

[EDIT2]
even setting client `cache_session=CachedSession(
        backend="filesystem",
        expire_after=timedelta(seconds=10))` to 10 seconds does not look it update the request

**Comment by N4S4** [comment]
ok i tested again with smaller setpoint `cache_session=CachedSession( backend="filesystem", expire_after=timedelta(seconds=5))` and looks like is working, not sure if the 30 seconds default works but is much longer if i dont set cache_session, however all good tnx
