### ISSUE TITLE
[Feature] Add possibility to bypass certificate verify

### ISSUE THREAD

**Issue by N4S4** [GrandMoff100/HomeAssistantAPI#148]
Good day,

what I am trying to do:
I am building an app which is in the same network of the Hass instance.
Home assistant is exposed to the web so it has an ssl certificate, 
when i make local requests I get an error :

`requests.exceptions.SSLError: HTTPSConnectionPool((Caused by SSLError(CertificateError("hostname not matching bla bla bla)))
`

I manually added to [rawclient.py on line 81](https://github.com/GrandMoff100/HomeAssistantAPI/blob/b8042bfbac9e9f0572dea68e119cd0453285442a/homeassistant_api/rawclient.py#L81)  to avoid the problem

```python
def request(
        self,
        path,
        method="GET",
        headers: Dict[str, str] = None,
        decode_bytes: bool = True,
        **kwargs,
    ) -> Any:
        """Base method for making requests to the api"""
        try:
            if self.global_request_kwargs is not None:
                kwargs.update(self.global_request_kwargs)
            logger.debug("%s request to %s", method, self.endpoint(path))
            if self.cache_session:
                resp = self.cache_session.request(
                    method,
                    self.endpoint(path),
                    headers=self.prepare_headers(headers),
                    verify=False   # -----------------------------------> verify False
                    **kwargs,
                )
        except requests.exceptions.Timeout as err:
            raise RequestTimeoutError(
                f'Home Assistant did not respond in time (timeout: {kwargs.get("timeout", 300)} sec)'
            ) from err
        return self.response_logic(response=resp, decode_bytes=decode_bytes)
```

is there any possibility to integrate the ability to set `verify=False`  in the Client class initialization?

and thank you for the api

**Comment by GrandMoff100** [comment]
What address are you using in your app to access Hass? Is it the local ip or the domain of the ssl certificate?

**Comment by N4S4** [comment]
is a local ip address, I see the solution would be in PR #145

**Comment by GrandMoff100** [comment]
The solution is actually to use the domain instead or disable serving your certificates in your `http` hass config entry. But if your app is more temporary then disabling ssl validation would be ideal.

**Comment by GrandMoff100** [comment]
I'm actively developing that ssl validation feature atm and should be shipped in the next release :)

**Comment by N4S4** [comment]
> The solution is actually to use the domain instead or disable serving your certificates in your `http` hass config entry. But if your app is more temporary then disabling ssl validation would be ideal.

I know but I need requests over local net instead of jumping over the web.

Thank you for the immediate response

**Comment by GrandMoff100** [comment]
You can setup a local dns server like DNSMasq or Adguard to resolve your domain to a local ip like me and hundreds of people have. That way you don't jump over the web but it stays local.

**Comment by N4S4** [comment]
Yeah I thought the same but issue would be if someone using the app does not have this setup would be cutted out

**Comment by GrandMoff100** [comment]
Checkout version `4.1.1` :)
