### ISSUE TITLE
[Library Bug] Receive pydantic error

### ISSUE THREAD

**Issue by fvalle1** [GrandMoff100/HomeAssistantAPI#151]
**Describe the bug**
 
```
File "/home/user/.local/lib/python3.9/site-packages/homeassistant_api/rawclient.py", line 213, in get_domain
    domains = self.get_domains()
  File "/home/user/.local/lib/python3.9/site-packages/homeassistant_api/rawclient.py", line 209, in get_domains
    return tuple(services)
  File "/home/user/.local/lib/python3.9/site-packages/homeassistant_api/mixins.py", line 18, in process_services_json
    domain.add_service(service_id, **data)
  File "/homeuser/.local/lib/python3.9/site-packages/homeassistant_api/models/domains.py", line 24, in add_service
    service_id: Service(
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Service
target -> entity

```
**To Reproduce**
```python
client = Client(host, token)
ent = client.get_entities()
self.switch_domain = client.get_domain("switch")
```

**Expected behavior**
create a list of switch domains

**Desktop (please complete the following information):**
- OS: Rocky Linux
- OS Version 8
- HomeAssistantAPI Version: 4.0.3

**Comment by fvalle1** [comment]
It seems a problem when using HA containerised and using a version greater then `ghcr.io/home-assistant/home-assistant:2023.3`

**Comment by fvalle1** [comment]
@fraaud keep an eye on this

**Comment by AquaMorph** [comment]
I also have run into this bug since I updated to the latest version of Home Assistant. It also does this on get_domain('light') as well.
Home Assistant: 2023.4.1
Supervisor: 2023.04.0
OS: Debian GNU/Linux 11 (bullseye)

**Comment by victormylle** [comment]
I have the same issue after updating home assistant

**Comment by GrandMoff100** [comment]
After doing some research it appears the service schema has changed and I don't know why yet. I will update this thread with other discoveries. We can probably fix this by the end of the day tomorrow.

**Comment by rozanski** [comment]
I get this error with get_domain('light') as well. I'm running HA  dockerised on Raspberry Pi. Was working fine until I upgraded. However I've tried downgrading the API version and still get the error. I went as far back as 2.2 something and then got an error to say that get_domain() doesn't exist. Happy to test if you issue an update.

**Comment by GrandMoff100** [comment]
Update on debugging: I've reproduced it in the testing suite.
```
homeassistantapi-tests-1   | =========================== short test summary info ============================
homeassistantapi-tests-1   | FAILED tests/test_endpoints.py::test_get_domains - pydantic.error_wrappers.Va...
homeassistantapi-tests-1   | FAILED tests/test_endpoints.py::test_async_get_domains - pydantic.error_wrapp...
homeassistantapi-tests-1   | FAILED tests/test_endpoints.py::test_get_domain - pydantic.error_wrappers.Val...
homeassistantapi-tests-1   | FAILED tests/test_endpoints.py::test_async_get_domain - pydantic.error_wrappe...
homeassistantapi-tests-1   | FAILED tests/test_endpoints.py::test_trigger_service - pydantic.error_wrapper...
homeassistantapi-tests-1   | FAILED tests/test_endpoints.py::test_async_trigger_service - pydantic.error_w...
homeassistantapi-tests-1   | FAILED tests/test_models.py::test_get_domain - pydantic.error_wrappers.Valida...
homeassistantapi-tests-1   | FAILED tests/test_models.py::test_async_get_domains - pydantic.error_wrappers...
homeassistantapi-tests-1   | ========================= 8 failed, 67 passed in 2.37s =========================
```

**Comment by GrandMoff100** [comment]
The new version `4.1.1.post1` will be on PyPI momentarily.
Feel free to confirm my testing and lemme know if it works for you guys.

**Comment by felix-redlich** [comment]
Can confirm it's working again. Thanks for the quick fix!

**Comment by AquaMorph** [comment]
Just updated to that version and it is also working for me. Thanks so much

**Comment by rozanski** [comment]
Yes it's working again for me too. Thanks also for the really quick fix!

**Comment by Fraaud** [comment]
I confirm that is working with the last stable release, thank you
