### ISSUE TITLE
ProcessorNotFoundError: No response processor found for mimetype 'text/plain; charset=utf-8'

### ISSUE THREAD

**Issue by jinglemansweep** [GrandMoff100/HomeAssistantAPI#154]
**Describe the bug**
After upgrading HASS to 2023.6.0, my previously working calls to `hass.get_rendered_template` are now failing with the following error:

    Traceback (most recent call last):
      File "entity_row.py", line 77, in render
        label = hass.get_rendered_template(template)
        ...
        raise ProcessorNotFoundError(
    homeassistant_api.errors.ProcessorNotFoundError: No response processor found for mimetype 'text/plain; charset=utf-8'.

**To Reproduce**
1. Upgrade HASS to 2023.6.0
2. Make a call using `hass_get_rendered_template()`
3. See error

**Expected behavior**

Call to `get_rendered_template()` should succeed

**Desktop (please complete the following information):**
- OS: Ubuntu
- OS Version: 22.04
- HomeAssistantAPI Version: 4.1.0

**Additional context**
I suspect that HASS API is now returning `charset=utf-8` in addition to the mimetype?

    curl -v -X POST -d '{"template": "hello"}' -H "Authorization: Bearer <REDACTED>" http://hass.home/api/template
    *   Trying 10.0.2.23:8123...
    > POST /api/template HTTP/1.1
    > Host: hass.home:8123
    > User-Agent: curl/7.81.0
    > Accept: */*
    > Authorization: Bearer <REDACTED>
    > Content-Length: 21
    > Content-Type: application/x-www-form-urlencoded
     
    < HTTP/1.1 200 OK
    < Content-Type: text/plain; charset=utf-8
    < Content-Length: 5
    < Date: Thu, 08 Jun 2023 20:17:46 GMT
    < Server: Python/3.11 aiohttp/3.8.4

**Comment by jinglemansweep** [comment]
PR: https://github.com/GrandMoff100/HomeAssistantAPI/pull/155

**Comment by GrandMoff100** [comment]
Awesome!

**Comment by GrandMoff100** [comment]
You got to this before me lol. Good job. Test suite is running right now. Once it passes we can merge the pr and deploy a patched version shortly thereafter.

**Comment by GrandMoff100** [comment]
Let me know if the new version `4.1.1.post2` works for you!

**Comment by jinglemansweep** [comment]
Works fine for me...

https://github.com/jinglemansweep/wideboy/commit/33da16377c0198be1f9669436d1b5251b8118bf0
