### ISSUE TITLE
Internal Server Error 500 when triggering service in Home Assistant API

### ISSUE THREAD

**Issue by konpyl** [GrandMoff100/HomeAssistantAPI#162]
**Describe the bug**

I encountered an error while using the Home Assistant API. Specifically, the error occurred when I tried to trigger a service. The traceback indicates that the error originated from the `async_trigger_service` method in the `rawasyncclient.py` file. The error message returned was '500 Internal Server Error\n\nServer got itself in trouble'. 

**To Reproduce**

```python
start = datetime.datetime.utcnow().replace(
    hour=0, minute=0, second=0, microsecond=0)

while start < datetime.datetime.utcnow():
    end = start + datetime.timedelta(days=1)

    calendar = 'calendar.xxx'
    service = await self.ha.api.async_get_domain("calendar")
    events = await service.list_events(
        entity_id=calendar,
        start_date_time=start,
        end_date_time=end,
    )
```

**Expected behavior**

I should get a list with events

**Desktop (please complete the following information):**

- OS: Mac
- OS Version 2023.9.3
- HomeAssistantAPI Version: 4.1.1.post2

**Comment by GrandMoff100** [comment]
Can you also send your homeassistant configuration.yaml?

**Comment by konpyl** [comment]
Hello @GrandMoff100 

Thank you for your quick response. I appreciate your help in resolving this issue. 

I've been exploring the Home Assistant API and found a dedicated endpoint call for this: `/api/calendars/<calendar entity_id>`. I'm curious, is this implemented in the SDK?

**Comment by GrandMoff100** [comment]
That is not currently implemented in the SDK. You're welcome to implement it though! But without the trace back in the homeassistant server logs I can't say for sure what's causing it.

**Comment by GrandMoff100** [comment]
Stale issue
