### ISSUE TITLE
[Library Bug] Exception has occurred: ProcessorNotFoundError

### ISSUE THREAD

**Issue by Bluscream** [GrandMoff100/HomeAssistantAPI#166]
**Describe the bug**
```
Exception has occurred: ProcessorNotFoundError
No response processor found for mimetype 'text/html'.
  File "P:\Python\hass\esphome_reverse.py", line 30, in main
    async with client:
  File "P:\Python\hass\esphome_reverse.py", line 37, in <module>
    loop.run_until_complete(main())
homeassistant_api.errors.ProcessorNotFoundError: No response processor found for mimetype 'text/html'.
```

**To Reproduce**
1. Run the example async client

**Expected behavior**
connection

**Screenshots**
![](https://i.imgur.com/ylRK90l.png)

**Desktop (please complete the following information):**
- OS: Win11
- OS Version 10.0.22621.2715
- HomeAssistantAPI Version: homeassistant-api-4.1.1.post2

**Comment by GrandMoff100** [comment]
Hello! Does your `HASS_URL` end with `/api` by chance?

**Comment by Bluscream** [comment]
It does not, thank you! Might wanna add that to the docs somewhere ^^
