### ISSUE TITLE
entity.get_state() - inconsistency with actual state, long loading time

### ISSUE THREAD

**Issue by kilian579** [GrandMoff100/HomeAssistantAPI#171]
**Describe the bug**
In some (not 100% reproducable) occasions, the `get_state()` function returns values, which are inconsistent witht the actual state of the entity. The problem can be fixed, by waiting a time of 2 seconds, up to 1 minute. After that, the method returns the correct values.

E.g. My light is at brightness 70, but get_state returns brightness 240.

This only occurs using this api. My homeassistant Web-Dashboard shows the correct value.
I have only worked with lights so far. Not sure if it also occurs with other entities.

**To Reproduce**
(works often)

--> Check brightness for consistency whenever calling get_state()
at some point it stops to update the brightness correctly 

1. Get current brightness using `get_state()`
2. Increase brightness by 10, by adding 10 to received value
3. Repeat steps 1 and 2 until brightness of 250 or 255 is reached
4. Get current brightness using `get_state()`
5. Decrease brightness by 10, by substracting 10 from received value
6. Repeat steps 4 and 5 until brightness of 5 or 0 is reached

**Expected behavior**
`get_state()` should return the values, that are currently representing the state of the entity.

**Screenshots**
(1)
<img width="1553" alt="hass_1" src="https://github.com/GrandMoff100/HomeAssistantAPI/assets/11147822/0d5f5855-0a12-429e-bc1b-cb29fa4abfcf">
(2)
<img width="1540" alt="hass_2" src="https://github.com/GrandMoff100/HomeAssistantAPI/assets/11147822/cadb1e24-24f8-47bd-9bd8-6b4c19a1953e">
(3)
<img width="266" alt="hass_3" src="https://github.com/GrandMoff100/HomeAssistantAPI/assets/11147822/85943838-32f2-4651-ba72-8cc2f6e7a0eb">

**Comment by GrandMoff100** [comment]
Thanks for opening this! Could tell me what versions of `homeassistant-api` and python you're using real quick?

**Comment by kilian579** [comment]
Tested on
Python 3.9.2 (and also 3.11.2)
homeassistant-api 4.1.1 (and also 4.2.1)

**Comment by GrandMoff100** [comment]
Alright, I think I might know what's happening. Just to test this hypothesis could you initialize your client with `Client(..., cache_session=False)` to disable caching?

Caching is enabled by default and I think that might be what's causing this. The [docs on caching](https://homeassistantapi.readthedocs.io/en/latest/advanced.html) are due for some more love anyway so I'll work on refreshing those to make them more clear.

**Comment by kilian579** [comment]
Seems to work now. I will more intensively test it again next week.

Thanks for the quick reply!

**Comment by GrandMoff100** [comment]
Closing because fixed and/or stale
