### ISSUE TITLE
[Library Bug] Administrator role now required

### ISSUE THREAD

**Issue by utkashd** [GrandMoff100/HomeAssistantAPI#173]
It seems that the latest version of Home Assistant requires the user to be an administrator. I believe previous versions of Home Assistant did not require this. My guess is the `/api/config/core/check_config` path used to not require an administrator and now it does.

```python
import os
from homeassistant_api import Client

with Client(
    api_url="https://[redacted]/api",
    token=os.environ["HA_TOKEN"],
) as client:
    print(client.get_config())
```

If the user (who has corresponding token `HA_TOKEN`) is not an administrator, the above results in a stacktrace that includes:

```python
...
File "homeassistant_api/rawclient.py", line 190, in check_api_config
    Dict[str, Any], self.request("config/core/check_config", method="POST")
...
File "homeassistant_api/processing.py", line 93, in process
    raise UnauthorizedError()
```

I confirmed my non-administrator token works with:

```bash
curl -X GET https://[redacted]/api/events -H "Authorization: Bearer ${HA_TOKEN}" -H 'Content-Type: application/json'
```

This request fails with a 401 if the user is not an administrator (and succeeds otherwise):

```bash
curl -X POST https://[redacted]/api/config/core/check_config -H "Authorization: Bearer ${HA_TOKEN}" -H 'Content-Type: application/json'
```

Version info:
- HomeAssistant-API: 4.2.1

- Core: 2024.3.0
- Supervisor: 2024.02.1
- Operating System: 12.0
- Frontend: 20240306.0

**Comment by GrandMoff100** [comment]
Good catch 👍 
Currently we check if home assistant is running by getting the config upon entering the session but now that this requires admin we should probably just remove that check to make it faster and make people call it manually if they need to.
I'll publish a fix tomorrow or the day after.

**Comment by GrandMoff100** [comment]
New version published. Let me know if it's fixed for you.

**Comment by utkashd** [comment]
Finally had a chance to test; upgraded to 4.2.2 and all seems to be functional with a non-admin token! Thanks for the quick turnaround and the well-written project
