### ISSUE TITLE
[Library Bug] client.get_events() fails with TypeError

### ISSUE THREAD

**Issue by flatsheep** [GrandMoff100/HomeAssistantAPI#24]
**Description**
After calling an an instance of a Client object: client.get_events() an error occurs.

**To Reproduce**
Steps to reproduce the behaviour:
1. create an instance of the client object
2. call client.get_events()
```
from homeassistant_api import Client

ha_url = 'http://192.168.1.xxx:8123/api'
ha_token = 'xxxxx'

client = Client(ha_url, ha_token)
client.get_events()
```

**Expected behaviour**
Should return a JsonModel of Event objects

**Trackback**
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/linuxmint/.local/lib/python3.9/site-packages/homeassistant_api/client.py", line 238, in get_events
>     data = [self.process_event_json(event_info) for event_info in data]
>   File "/home/linuxmint/.local/lib/python3.9/site-packages/homeassistant_api/client.py", line 238, in <listcomp>
>     data = [self.process_event_json(event_info) for event_info in data]
>   File "/home/linuxmint/.local/lib/python3.9/site-packages/homeassistant_api/client.py", line 41, in process_event_json
>     return Event(**json)
> TypeError: __init__() missing 1 required positional argument: 'client'

**Environment**
 - OS: Mint
 - Python Version 3.9 (also tried 3.7)
 - HomeAssistantAPI Version: 2.2.0
 - HomeAssistant Version: 2021.8.5

**Potential cause**
Reviewing the Traceback, I noted the Event object expects a client argument that isn't passed through, I amended the client.py code as a workaround:
```
 # Event methods
 def get_events(self) -> JsonModel:
        """Gets the Events that happen within homeassistant"""
        data = self.request('events')
        # append the client reference onto each event
        data = [dict(event, client=self) for event in data]
        events = [self.process_event_json(event_info) for event_info in data]
        events = {evt.event_type: evt for evt in events}
        return JsonModel(events)
```
The single additional line of code after the _# append_ comment adds the reference to the client object to each dictionary.  This fixes the issue and the code then works as required. Sorry I haven't got time to fork and amend myself, not sure if this is the way you'd fix the issue anyway.

**Comment by GrandMoff100** [comment]
Great issue. Glad you caught it! I've tested it and it works too. You don't need open a PR and amend it yourself because this will be fixed in the next release in a few days. This bug may also apply to the async side of this library. I will be looking into this issue more to see what else across the library might be affected by the bug. But thanks for reporting this!
