### ISSUE TITLE
[Library Bug] RecursionError calling domain action, e.g. light.turn_on.trigger(entity_id='light.my_light')

### ISSUE THREAD

**Issue by flatsheep** [GrandMoff100/HomeAssistantAPI#26]
**Description**
As per the first example on the docs page: https://homeassistantapi.readthedocs.io/en/latest/.  Calling `light.turn_on.trigger(entity_id='light.my_light')` causes the following Trackback:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/linuxmint/.local/lib/python3.9/site-packages/homeassistant_api/models/domains.py", line 35, in __getattr__
    if hasattr(self, attr):
  File "/home/linuxmint/.local/lib/python3.9/site-packages/homeassistant_api/models/domains.py", line 35, in __getattr__
    if hasattr(self, attr):
  File "/home/linuxmint/.local/lib/python3.9/site-packages/homeassistant_api/models/domains.py", line 35, in __getattr__
    if hasattr(self, attr):
  [Previous line repeated 497 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Environment**
 - OS: Mint
 - Python 3.9
 - HomeAssistant Version: 2021.8.5
 - HomeAssistantAPI Version: 2.2.0

**Resolution**
In models/domains.py, Domain object, \_\_getattr\_\_ function, amend as follows:

```
    def __getattr__(self, attr: str):
        """Allows services accessible as attributes"""
        if attr in self.__dict__: #hasattr(self, attr):
            return super().__getattribute__(attr)
        if attr in self.services:
            return self.get_service(attr)
        return super().__getattribute__(attr)
```

Calling hasattr function causes recursion as this function itself calls \_\_getattr\_\_. As an alternative, test within self.\_\_dict\_\_ resolves the problem and the functionality is restored.

**Workaround**
In the meantime, it's possible to call: `light.get_service('turn_on').trigger(entity_id='light.my_lamp')` to achieve the same behaviour, without having to modify the underlying code.

**Comment by GrandMoff100** [comment]
Thanks for letting me know. I agree, checking `__dict__` would solve the problem. I have a few other ideas as well. I'll get right on it.
