### ISSUE TITLE
'Service' object is not callable

### ISSUE THREAD

**Issue by walking-octopus** [GrandMoff100/HomeAssistantAPI#48]
**Describe the bug**
Attempting to call a service object throws a `'Service' object is not callable` error.

**To Reproduce**
1. Run the quick example. `services.light.turn_on(entity_id='light.living_room_lamp')`
2. See an error

**Expected behavior**
`light.living_room_lamp` turns off.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - HomeAssistantAPI Version: 2.4.0.post2

**Comment by GrandMoff100** [comment]
Yep that is error is correct.

The correct usage is

`services.light.turn_on.trigger(entity_id='light.living_room_lamp')`

I'll update the quick example.

Sorry! :)

**Comment by walking-octopus** [comment]
Thanks for help!

**Comment by GrandMoff100** [comment]
But that's a great idea for a feature


We can make Service objects callable by just adding a `__call__` method that'll just be alias for `.trigger()`

I'll go implement it quick.

**Comment by GrandMoff100** [comment]
That way the example I had before could actually work lol.
