### ISSUE TITLE
API Key in Examples

### ISSUE THREAD

**Issue by conor-f** [GrandMoff100/HomeAssistantAPI#49]
An API key has accidentally been left in [this example](https://github.com/GrandMoff100/HomeAssistantAPI/blob/master/examples/set_sensors.py#L5).

**Comment by GrandMoff100** [comment]
Yep that key *was* left there, but because that token was revoked right afterwards, and that that development environment no longer exists I think it's pretty safe to keep it like that, and also serves as an example to what a token looks like in practice.
