### ISSUE TITLE
Incorrect key in Entity model

### ISSUE THREAD

**Issue by kennyboy55** [GrandMoff100/HomeAssistantAPI#94]
https://github.com/GrandMoff100/HomeAssistantAPI/blob/c38d21cacb5798d714e1fe4e2be823edf67b771a/homeassistant_api/models/entity.py#L28

`File "<redacted>\homeassistant_api\rawclient.py", line 153, in get_entities
    entities[group_id].add_entity(entity_slug, state)
  File "<redacted>\homeassistant_api\models\entity.py", line 25, in add_entity
    self.entities[entity_slug] = Entity(
  File "pydantic\main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Entity
group
  field required (type=value_error.missing)
`

The line should say:
`group=self,`

**Comment by GrandMoff100** [comment]
You're right this is in issue. But it's actually `client=self.client`.

I'll get right on this!
