### ISSUE TITLE
[Library Bug]

### ISSUE THREAD

**Issue by elanworld** [GrandMoff100/HomeAssistantAPI#98]
http api path error in windows

join error ,such as api/states/entity_id instead of api/states\\?entity_id

**Comment by GrandMoff100** [comment]
Could you elaborate on and/or paste what error trackbacks you're getting as well as what Python version and HomeAssistantAPI version you're have installed and running?

Thank you!

**Comment by elanworld** [comment]
> Could you elaborate on and/or paste what error trackbacks you're getting as well as what Python version and HomeAssistantAPI version you're have installed and running?
> 
> Thank you!

i use python 3.8.0 in windwos
package named homeassistant-api:3.0.3,in the rawclinet.py file
like
def trigger_service(
        self,
        domain: str,
        service: str,
        **service_data,
    ) -> Tuple[State, ...]:
        """Tells Home Assistant to trigger a service, returns stats changed while being called"""
        data = self.request(
            join("services", domain, service),
            method="POST",
            json=service_data,
        )
        states = map(self.process_state_json, cast(List[Dict[str, Any]], data))
        return tuple(states)

but the join variable is
"from os.path import join"

the url will be xxx\xxx

**Comment by GrandMoff100** [comment]
Ah okay. I see.

In that case we just need to replace that with urljoin from urllib.
